--- #YAML:1.0

meta-spec:
   version: 1.4
   url: http://module-build.sourceforge.net/META-spec-v1.4.html

name: tie-multikeyinsertorderhash
version: 0.1
abstact: Hash that save multiple keys in insertion order
author:
 - Marc Lucksch <perl@maluku.de>

license:
  perl

distribution_type: module

requires:
  Tie::Hash: 0

provides:
  Tie::MultiKeyInsertOrderHash:
    file: lib/Tie/MultiKeyInsertOrderHash.pm
    version: "0.1"
